import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { UserIcon } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white border-b border-gold-200 px-6 py-4">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <h1 className="text-xl font-bold text-foreground">Meillor</h1>
            <div className="flex items-center gap-3">
              <Link href="/login">
                <Button variant="outline" size="default" className="hover:bg-gold-50 hover:border-gold-500">
                  Se connecter
                </Button>
              </Link>
              <Link href="/register">
                <Button size="default" className="bg-gold-500 hover:bg-gold-600 hover:text-black">
                  <UserIcon className="w-4 h-4 mr-2" />
                  Devenir Membre
                </Button>
              </Link>
            </div>
          </div>
        </header>
        <main className="max-w-7xl xl:px-0 px-6 mt-6 mx-auto bg-white">
          {children}
        </main>
      </body>
    </html>
  );
}
